### ISSUE TITLE
File not generated

### ISSUE THREAD

**Issue by cshold** [graygilmore/grunt-shopify-sass#5]
I've tried the two following setups and the dist file doesn't seem to get generated. Am I doing something wrong?

```
shopify_sass:
  options:
    base: 'src/stylesheets'
  files:
    'assets/timber.scss.liquid': 'timber.scss'
```

```
shopify_sass:
  files:
    'assets/timber.scss.liquid': 'src/stylesheets/timber.scss'
```
